"""Analysis and pattern models."""
from sqlalchemy import Column, String, Integer, JSON, ForeignKey, Float, DateTime, Boolean
from sqlalchemy.orm import relationship
from app.models.base import Base, TimestampMixin


class MessageAnalysis(Base, TimestampMixin):
    """Analysis of individual message."""
    __tablename__ = "message_analyses"
    
    student_id = Column(String, ForeignKey("students.student_id"), nullable=False)
    session_id = Column(Integer, ForeignKey("sessions.id"))
    message_id = Column(String, nullable=False)
    message_text = Column(String, nullable=False)
    
    # Analysis results
    emoji_analysis = Column(JSON)  # Emoji interpretation results
    sentiment_score = Column(Float)
    concern_indicators = Column(JSON, default=list)  # List of flagged concerns
    safety_flags = Column(JSON, default=list)  # Immediate safety concerns
    
    # Processing metadata
    checkpoint_results = Column(JSON)  # Results from each checkpoint
    processing_time_ms = Column(Integer)


class TemporalPattern(Base, TimestampMixin):
    """Temporal pattern detection results."""
    __tablename__ = "temporal_patterns"
    
    student_id = Column(String, ForeignKey("students.student_id"), nullable=False)
    pattern_type = Column(String, nullable=False)  # "rapid_deterioration", "pre_decision_calm", etc.
    detected_at = Column(DateTime, nullable=False)
    pattern_data = Column(JSON, nullable=False)  # Velocity, acceleration, history
    risk_multiplier = Column(Float, default=1.0)
    alert_generated = Column(Boolean, default=False)


class Alert(Base, TimestampMixin):
    """Alert record."""
    __tablename__ = "alerts"
    
    student_id = Column(String, ForeignKey("students.student_id"), nullable=False)
    alert_type = Column(String, nullable=False)  # "IMMEDIATE", "URGENT", "ROUTINE"
    risk_profile_id = Column(Integer, ForeignKey("risk_profiles.id"))
    message = Column(String, nullable=False)
    routing_status = Column(String, default="PENDING")  # "PENDING", "REVIEWED", "RESOLVED"
    counselor_id = Column(String)
    reviewed_at = Column(DateTime)
    
    # Outcome tracking fields
    counseling_appointment_scheduled = Column(Boolean, default=False)
    counseling_appointment_attended = Column(Boolean, nullable=True)
    appointment_scheduled_at = Column(DateTime, nullable=True)
    appointment_attended_at = Column(DateTime, nullable=True)
    
    # Relationships
    outcome = relationship("InterventionOutcome", back_populates="alert", uselist=False)


class CrisisAnalytics(Base, TimestampMixin):
    """Comprehensive analytics data for crisis protocol cases."""
    __tablename__ = "crisis_analytics"
    
    student_id = Column(String, ForeignKey("students.student_id"), nullable=False)
    alert_id = Column(Integer, ForeignKey("alerts.id"), nullable=True)
    
    # Student profile data
    student_profile = Column(JSON, nullable=False)  # Full student profile info
    
    # Message history and analysis
    recent_messages = Column(JSON, default=list)  # Last 20-30 messages with analysis
    message_analyses = Column(JSON, default=list)  # All message analyses
    
    # Risk assessment data
    risk_profiles = Column(JSON, default=list)  # All risk profiles
    current_risk_profile = Column(JSON, nullable=True)  # Most recent risk profile
    
    # Assessment data
    assessments = Column(JSON, default=list)  # PHQ-9, GAD-7, C-SSRS assessments
    temporal_patterns = Column(JSON, default=list)  # Detected patterns
    
    # Session data
    session_summary = Column(JSON, nullable=True)  # Session count, engagement patterns
    
    # Behavioral metadata
    behavioral_metadata = Column(JSON, default=dict)  # Engagement, response times, etc.
    
    # Priority level (for sorting in admin dashboard)
    priority = Column(String, default="HIGH")  # "CRITICAL", "HIGH", "MEDIUM"
    
    # Crisis trigger details
    trigger_reason = Column(String, nullable=False)
    trigger_message = Column(String, nullable=True)
    
    # Relationships
    student = relationship("Student", foreign_keys=[student_id])


class CrisisReport(Base, TimestampMixin):
    """Word summary report for crisis cases."""
    __tablename__ = "crisis_reports"
    
    student_id = Column(String, ForeignKey("students.student_id"), nullable=False)
    analytics_id = Column(Integer, ForeignKey("crisis_analytics.id"), nullable=True)
    alert_id = Column(Integer, ForeignKey("alerts.id"), nullable=True)
    
    # Report content
    summary = Column(String, nullable=False)  # Word summary generated by LLM
    key_findings = Column(JSON, default=list)  # Key points extracted
    recommended_actions = Column(JSON, default=list)  # Recommended interventions
    
    # Report metadata
    report_type = Column(String, default="CRISIS")  # "CRISIS", "HIGH_RISK", "ROUTINE"
    generated_by = Column(String, default="SYSTEM")  # "SYSTEM" or counselor ID
    
    # Relationships
    student = relationship("Student", foreign_keys=[student_id])
    analytics = relationship("CrisisAnalytics", foreign_keys=[analytics_id])




